"""Daytona — run AI-generated code in a secure sandbox. Falls back to a local
sandboxed exec of our own valuation snippet. `pip install daytona`, auth via
DAYTONA_API_KEY. Verified call: sandbox.process.code_run(code).result."""
import asyncio
import contextlib
import io

from .. import config


async def run_code(code: str) -> dict:
    """Return {stdout: str, source: 'live'|'mock'}."""
    if config.LIVE["daytona"]:
        try:
            out = await asyncio.to_thread(_live, code)
            return {"stdout": out, "source": "live"}
        except Exception as e:
            return {"stdout": _local(code), "source": "mock", "note": f"live failed: {type(e).__name__}"}
    return {"stdout": _local(code), "source": "mock"}


def _live(code: str) -> str:
    from daytona import Daytona  # lazy; reads DAYTONA_API_KEY

    daytona = Daytona()
    sandbox = daytona.create()
    try:
        return sandbox.process.code_run(code).result
    finally:
        sandbox.delete()


def _local(code: str) -> str:
    """Run our own valuation arithmetic locally, capturing stdout. The code is
    generated by us (deterministic arithmetic), not the model, so exec is safe."""
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        exec(code, {"__builtins__": __builtins__})  # noqa: S102 — our own snippet
    return buf.getvalue().strip()
